theme = "base16_eighties"

[editor]
auto-pairs = false
auto-save = true
bufferline = "always"
end-of-line-diagnostics = "disable"
idle-timeout = 250
rulers = [80, 100]
true-color = true

[editor.indent-guides]
render = false
character = "·"

[editor.inline-diagnostics]
cursor-line = "warning"
other-lines = "disable"

[editor.whitespace.render]
newline = "none"
space = "none"
tab = "none"

[editor.whitespace.characters]
newline = "↩"
space = "·"
tab = "↦"

[keys.normal]
"$" = "goto_line_end"
"^" = "goto_first_nonwhitespace"
"0" = "goto_line_start"
"H" = ":reflow"
"A-w" = [ "move_prev_word_start", "move_next_word_end" ]
"C-h" = "jump_view_left"
"C-j" = "jump_view_down"
"C-k" = "jump_view_up"
"C-l" = "jump_view_right"
"C-q" = ":buffer-close"
"C-r" = ":reload"
 
[keys.select]
"$" = "goto_line_end"
