"diagnostic" = { underline = { style = "curl", color = "base03" } }
"diagnostic.info" = { underline = { style = "curl", color = "base0D" } }
"diagnostic.warning" = { underline = { style = "curl", color = "base08" } }
"diagnostic.error" = { underline = { style = "curl", color = "base09" } }

"diff.delta" = { fg = "base09" }
"diff.minus" = { fg = "base08" }
"diff.plus" = { fg = "base0B" }

"debug" = "base03"
"error" = "base08"
"hint" = "base03"
"info" = "base0D"
"label" = "base0E"
"warning" = "base09"

"markup.bold" = { fg = "base0A", modifiers = ["bold"] }
"markup.heading" = "base0D"
"markup.italic" = { fg = "base0E", modifiers = ["italic"] }
"markup.link.text" = "base08"
"markup.link.url" = { fg = "base09", underline = { style = "line" } }
"markup.list" = "base08"
"markup.quote" = "base0C"
"markup.raw" = "base0B"

"attributes" = "base09"
"comment" = { fg = "base03", modifiers = ["italic"] }
"constant" = "base09"
"constant.character.escape" = "base0C"
"constant.numeric" = "base09"
"constructor" = "base0D"
"function" = "base0D"
"keyword" = "base0E"
"namespace" = "base0E"
"operator" = "base05"
"special" = "base0D"
"string"  = "base0B"
"type" = "base0A"
"variable" = "base08"
"variable.other.member" = "base0B"

"ui.background" = { bg = "base00" }
"ui.bufferline" = { fg = "base03", bg = "base01" }
"ui.bufferline.active" = { fg = "base04" }
"ui.cursor" = { fg = "base04", modifiers = ["reversed"] }
"ui.cursor.match" = { fg = "base0A", underline = { style = "line" } }
"ui.cursor.primary" = { fg = "base05", modifiers = ["reversed"] }
"ui.cursorline.primary" =  { bg = "base01" }
"ui.cursorline.secondary" =  { bg = "base00" }
"ui.gutter" = { bg = "base00" }
"ui.help" = { fg = "base06", bg = "base01" }
"ui.linenr" = { fg = "base03", bg = "base00" }
"ui.linenr.selected" = { fg = "base04", bg = "base01", modifiers = ["bold"] }
"ui.menu" = { fg = "base05", bg = "base01" }
"ui.menu.selected" = { fg = "base01", bg = "base04" }
"ui.popup" = { bg = "base01" }
"ui.selection" = { bg = "base02" }
"ui.statusline" = { fg = "base04", bg = "base01" }
"ui.text" = "base05"
"ui.text.focus" = "base05"
"ui.virtual.ruler" = { bg = "base01" }
"ui.virtual.whitespace" = { fg = "base03" }
"ui.window" = { bg = "base00", fg = "base01" }

[palette]
base00 = "#2d2d2d" # Default Background
base01 = "#393939" # Lighter Background (Used for status bars, line number and folding marks)
base02 = "#515151" # Selection Background
base03 = "#747369" # Comments, Invisibles, Line Highlighting
base04 = "#a09f93" # Dark Foreground (Used for status bars)
base05 = "#d3d0c8" # Default Foreground, Caret, Delimiters, Operators
base06 = "#e8e6df" # Light Foreground (Not often used)
base07 = "#f2f0ec" # Light Background (Not often used)
base08 = "#f2777a" # Variables, XML Tags, Markup Link Text, Markup Lists, Diff Deleted
base09 = "#f99157" # Integers, Boolean, Constants, XML Attributes, Markup Link Url
base0A = "#ffcc66" # Classes, Markup Bold, Search Text Background
base0B = "#99cc99" # Strings, Inherited Class, Markup Code, Diff Inserted
base0C = "#66cccc" # Support, Regular Expressions, Escape Characters, Markup Quotes
base0D = "#6699cc" # Functions, Methods, Attribute IDs, Headings
base0E = "#cc99cc" # Keywords, Storage, Selector, Markup Italic, Diff Changed
base0F = "#d27b53" # Deprecated, Opening/Closing Embedded Language Tags, e.g. <?php ?>
